// Build step (source-time only, never runs in the game): read the 24 authored hero frames
// from assets/hero/*.png, knock out the magenta edge matte, trim transparent margins, and
// splice a base64 data-URI block into index.html between the HERO_B64 markers.
//
//   node test/inline-hero.js
//
// The PNGs are SOURCE (like test/): the shipped game is still one self-contained index.html
// with the frames inlined, no runtime asset fetch.
const fs = require('fs');
const path = require('path');
const { PNG } = require('pngjs');

const DIR = path.resolve(__dirname, '..', 'assets', 'hero');
const HTML = path.resolve(__dirname, '..', 'index.html');

// animation -> ordered frame basenames
const GROUPS = {
  idle: ['idle_0', 'idle_1', 'idle_2', 'idle_3'],
  walk: ['walk_0', 'walk_1', 'walk_2', 'walk_3', 'walk_4', 'walk_5'],
  atk1: ['attack1_0', 'attack1_1', 'attack1_2', 'attack1_3'],
  atk2: ['attack2_0', 'attack2_1', 'attack2_2', 'attack2_3'],
  sp:   ['special_0', 'special_1', 'special_2', 'special_3', 'special_4', 'special_5'],
};

// The frames were matted against magenta; the fringe survives as a ring of opaque
// magenta-ish pixels (r~b high, g low). Zero their alpha so the HD downscale has no halo.
function isMagenta(r, g, b) {
  return b > 110 && r > 110 && g < 0.75 * Math.min(r, b) && Math.abs(r - b) < 80;
}

function processFrame(file) {
  const src = PNG.sync.read(fs.readFileSync(path.join(DIR, file + '.png')));
  const { width: W, height: H, data } = src;
  // 1) magenta knockout
  let knocked = 0;
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] > 0 && isMagenta(data[i], data[i + 1], data[i + 2])) { data[i + 3] = 0; knocked++; }
  }
  // 2) bounding box of the remaining opaque content
  let minx = W, miny = H, maxx = -1, maxy = -1;
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (data[(y * W + x) * 4 + 3] > 0) {
      if (x < minx) minx = x; if (x > maxx) maxx = x;
      if (y < miny) miny = y; if (y > maxy) maxy = y;
    }
  }
  const cw = maxx - minx + 1, ch = maxy - miny + 1;
  const out = new PNG({ width: cw, height: ch });
  for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) {
    const s = ((y + miny) * W + (x + minx)) * 4, d = (y * cw + x) * 4;
    out.data[d] = data[s]; out.data[d + 1] = data[s + 1];
    out.data[d + 2] = data[s + 2]; out.data[d + 3] = data[s + 3];
  }
  const buf = PNG.sync.write(out, { colorType: 6 });
  return { b64: 'data:image/png;base64,' + buf.toString('base64'), cw, ch, knocked, bytes: buf.length };
}

let total = 0, count = 0;
const lines = ['/*HERO_B64_START — generated by test/inline-hero.js, do not edit by hand*/',
  'const HERO_B64 = {'];
for (const key of Object.keys(GROUPS)) {
  const parts = [];
  for (const f of GROUPS[key]) {
    const r = processFrame(f);
    parts.push('"' + r.b64 + '"');
    total += r.bytes; count++;
    console.error(`${f}: ${r.cw}x${r.ch}  knockout ${r.knocked}px  ${(r.bytes / 1024).toFixed(1)}KB`);
  }
  lines.push('  ' + key + ': [\n    ' + parts.join(',\n    ') + '\n  ],');
}
lines.push('};');
lines.push('/*HERO_B64_END*/');
const block = lines.join('\n');

let html = fs.readFileSync(HTML, 'utf8');
const startRe = /\/\*HERO_B64_START[\s\S]*?\/\*HERO_B64_END\*\//;
if (!startRe.test(html)) {
  console.error('ERROR: HERO_B64 markers not found in index.html — add the placeholder first.');
  process.exit(1);
}
html = html.replace(startRe, block);
fs.writeFileSync(HTML, html);
console.error(`\nInlined ${count} frames, ${(total / 1024).toFixed(1)}KB of PNG (before base64), spliced into index.html.`);
