// Build step (source-time only, never runs in the game): the world's authored sprite sheets.
// Generalises test/inline-hero.js to any folder + variable name: read the sliced PNGs, knock
// out the magenta edge matte, trim transparent margins, re-encode, and splice a base64
// data-URI block into index.html between the <NAME>_B64_START / _END markers.
//
//   node test/inline-sheets.js            (regenerates every sheet whose markers exist)
//   node test/inline-sheets.js MOB DROP   (only the named sheets)
//
// The PNGs are SOURCE (like test/): the shipped game stays one self-contained index.html
// with the frames inlined, no runtime asset fetch. Same magenta-knockout as the hero.
const fs = require('fs');
const path = require('path');
const { PNG } = require('pngjs');

const HTML = path.resolve(__dirname, '..', 'index.html');
const A = function (d) { return path.resolve(__dirname, '..', 'assets', d); };

// name a range helper: rng('smog', 0, 5) -> ['smog_0'..'smog_5']
function rng(base, a, b) { const o = []; for (let i = a; i <= b; i++) o.push(base + '_' + i); return o; }

// Each sheet: marker var name, source dir, and either grouped frames (object of arrays) or a
// flat frame list. Frame order is the game's own (see the loaders/blits in index.html).
const SHEETS = {
  MOB:   { dir: 'monsters', groups: { smog: rng('smog', 0, 5), drum: rng('drum', 0, 5), cash: rng('cash', 0, 5) } },
  DROP:  { dir: 'items',    flat: rng('drop', 0, 2) },
  NPC:   { dir: 'npcs',     groups: { npcA: rng('npcA', 0, 5), npcB: rng('npcB', 0, 5), dog: rng('dog', 0, 3) } },
  DECOR: { dir: 'decor',    flat: rng('decor', 0, 7) },
  UI:    { dir: 'items',    flat: rng('ui', 0, 6) },
};

// The frames were matted against magenta; the fringe survives as a ring of opaque magenta-ish
// pixels (r~b high, g low). Zero their alpha so the HD downscale has no halo. (Same test the
// hero uses; soft-edged art like smoke keeps a wider pink halo, hence the tolerant bounds.)
function isMagenta(r, g, b) {
  return b > 100 && r > 100 && g < 0.80 * Math.min(r, b) && Math.abs(r - b) < 90;
}

function processFrame(dir, file) {
  const src = PNG.sync.read(fs.readFileSync(path.join(A(dir), file + '.png')));
  const { width: W, height: H, data } = src;
  let knocked = 0;
  for (let i = 0; i < data.length; i += 4) {
    if (data[i + 3] > 0 && isMagenta(data[i], data[i + 1], data[i + 2])) { data[i + 3] = 0; knocked++; }
  }
  let minx = W, miny = H, maxx = -1, maxy = -1;
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (data[(y * W + x) * 4 + 3] > 0) {
      if (x < minx) minx = x; if (x > maxx) maxx = x;
      if (y < miny) miny = y; if (y > maxy) maxy = y;
    }
  }
  if (maxx < 0) { minx = miny = 0; maxx = maxy = 0; }   // fully transparent guard
  const cw = maxx - minx + 1, ch = maxy - miny + 1;
  const out = new PNG({ width: cw, height: ch });
  for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) {
    const s = ((y + miny) * W + (x + minx)) * 4, d = (y * cw + x) * 4;
    out.data[d] = data[s]; out.data[d + 1] = data[s + 1];
    out.data[d + 2] = data[s + 2]; out.data[d + 3] = data[s + 3];
  }
  const buf = PNG.sync.write(out, { colorType: 6 });
  return { b64: 'data:image/png;base64,' + buf.toString('base64'), cw, ch, knocked, bytes: buf.length };
}

function frameList(sheet, cb) {                          // walk frames, callback -> b64 string
  if (sheet.flat) return '[\n    ' + sheet.flat.map(function (f) { return cb(f); }).join(',\n    ') + '\n  ]';
  const parts = [];
  for (const key of Object.keys(sheet.groups)) {
    const inner = sheet.groups[key].map(function (f) { return cb(f); });
    parts.push('  ' + key + ': [\n    ' + inner.join(',\n    ') + '\n  ]');
  }
  return '{\n' + parts.join(',\n') + '\n}';
}

let html = fs.readFileSync(HTML, 'utf8');
const only = process.argv.slice(2).map(function (s) { return s.toUpperCase(); });
let grandTotal = 0, grandCount = 0, touched = 0;

for (const name of Object.keys(SHEETS)) {
  if (only.length && only.indexOf(name) < 0) continue;
  const startRe = new RegExp('/\\*' + name + '_B64_START[\\s\\S]*?/\\*' + name + '_B64_END\\*/');
  if (!startRe.test(html)) { if (only.length) console.error('skip ' + name + ': markers not in index.html'); continue; }
  const sheet = SHEETS[name];
  let total = 0, count = 0;
  const body = frameList(sheet, function (f) {
    const r = processFrame(sheet.dir, f);
    total += r.bytes; count++;
    console.error(`${name}/${f}: ${r.cw}x${r.ch}  knockout ${r.knocked}px  ${(r.bytes / 1024).toFixed(1)}KB`);
    return '"' + r.b64 + '"';
  });
  const block = '/*' + name + '_B64_START — generated by test/inline-sheets.js, do not edit by hand*/\n' +
    'const ' + name + '_B64 = ' + body + ';\n' +
    '/*' + name + '_B64_END*/';
  html = html.replace(startRe, block);
  grandTotal += total; grandCount += count; touched++;
  console.error(`  -> ${name}: ${count} frames, ${(total / 1024).toFixed(1)}KB PNG (pre-base64)\n`);
}

fs.writeFileSync(HTML, html);
console.error(`Spliced ${touched} sheet(s), ${grandCount} frames, ${(grandTotal / 1024).toFixed(1)}KB of PNG into index.html.`);
